theme: jekyll-theme-minimal
title: Mitchell Harris
description: Applied Math PhD Student at MIT
logo: https://github.com/harris-mit/harris-mit.github.io/blob/f88d938228dbb617a7c42f1a18ad01d9aab3a121/assets/headshot-mitchell-harris.png
show_downloads: false
google_analytics: G-Q82VG5ZXJX
