theme: jekyll-theme-minimal
title: Mitchell Harris
description: Applied Math PhD Student at MIT
logo: https://media.licdn.com/dms/image/D4E03AQE4mamWfxtYug/profile-displayphoto-shrink_400_400/0/1699649293834?e=1704931200&v=beta&t=CH7HsJRVOakHPkgVdSYN-ejASHpWAqFqmOWOf3vr_JE
show_downloads: false
google_analytics: G-Q82VG5ZXJX